version: '3.7'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=P@55w0rd
      - POSTGRES_DB=misp-emf
      - POSTGRES_DB_SCHEMA=emf

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_SCHEMA: public
      DB_DATABASE: keycloak_db
      DB_USER: user
      DB_PASSWORD: P@55w0rd
      KEYCLOAK_USER: admin
      KEYCLOAK_HOSTNAME: localhost
      KEYCLOAK_PASSWORD: P@55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres
    command: "start-dev"